name: "Debug"
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Example param'
        required: true
      param2:
        description: 'Another example param'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Debug"
        run: echo ${{ toJSON(github.event.inputs) }}
