name: "Multiple triggers example"
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Debug"
        env:
          COMMAND: ${{ github.event.inputs.command || github.event.comment.body }}
        run: echo $COMMAND
