name: "Workflow dispatch example"
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Reference date in YYYY-MM-DD format, defaults to yesterday'
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -d 'yesterday 13:00' +'%Y-%m-%d')"
      - name: "Hello!"
        env:
          REFERENCE_DATE: ${{ github.event.inputs.date || steps.date.outputs.date }}
        run: echo $REFERENCE_DATE
